server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SMonasterio/movies-seriesConfig.git
          searchPaths: config

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: config-service
    description: Config service.
    version: 1.0.0
